// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod brolga {
    pub mod plugin {
        /// Structured failure returned across the ABI. Codes are stable; messages are diagnostic.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct PluginError {
                /// Stable machine code, for example `unsupported-contract` or `limit-exceeded`.
                pub code: _rt::String,
                /// Human-readable detail. Must not contain secrets or host paths the plugin was not given.
                pub message: _rt::String,
            }
            impl ::core::fmt::Debug for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PluginError")
                        .field("code", &self.code)
                        .field("message", &self.message)
                        .finish()
                }
            }
            impl ::core::fmt::Display for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for PluginError {}
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod brolga {
        pub mod plugin {
            /// Manifest export: every component answers who it is without side effects.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod manifest {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PluginError = super::super::super::super::brolga::plugin::types::PluginError;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::brolga::plugin::types::PluginError {
                                code: code3,
                                message: message3,
                            } = e;
                            let vec4 = (code3.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                            let vec5 = (message3.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr1
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr1
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                            let l5 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l5, l6, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Return the plugin manifest as UTF-8 JSON (`brolga.plugin.manifest/1.0`).
                    ///
                    /// The host validates the document before any `invoke.call`. A component that cannot
                    /// produce a valid manifest is refused rather than run on a guess.
                    fn get() -> Result<_rt::String, PluginError>;
                }
                #[doc(hidden)]
                macro_rules! __export_brolga_plugin_manifest_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "brolga:plugin/manifest@0.1.0#get")] unsafe extern "C" fn
                        export_get() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_get_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_brolga:plugin/manifest@0.1.0#get")] unsafe extern "C"
                        fn _post_return_get(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_get::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_brolga_plugin_manifest_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 5 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 5
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// The single portable call path. Extension-specific shapes live in the JSON body.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod invoke {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PluginError = super::super::super::super::brolga::plugin::types::PluginError;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_call_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let len2 = arg5;
                    let result3 = T::call(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                        _rt::Vec::from_raw_parts(arg4.cast(), len2, len2),
                    );
                    let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result3 {
                        Ok(e) => {
                            *ptr4.add(0).cast::<u8>() = (0i32) as u8;
                            let vec5 = (e).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr4
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr4
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                        Err(e) => {
                            *ptr4.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::brolga::plugin::types::PluginError {
                                code: code6,
                                message: message6,
                            } = e;
                            let vec7 = (code6.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *ptr4
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *ptr4
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr7.cast_mut();
                            let vec8 = (message6.into_bytes()).into_boxed_slice();
                            let ptr8 = vec8.as_ptr().cast::<u8>();
                            let len8 = vec8.len();
                            ::core::mem::forget(vec8);
                            *ptr4
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len8;
                            *ptr4
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr8.cast_mut();
                        }
                    };
                    ptr4
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_call<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                            let l6 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l7 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l6, l7, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Call one extension point with a deterministic JSON request body.
                    ///
                    /// - `extension` is the snake_case extension-point name (parser, exporter, …).
                    /// - `contract-version` is that point's `major.minor` contract tag.
                    /// - `request` is UTF-8 JSON whose schema is defined by the contract version.
                    ///
                    /// Success bytes are UTF-8 JSON. Failure is a structured `plugin-error`.
                    /// Unknown extension names and unsupported contract majors must fail clearly.
                    fn call(
                        extension: _rt::String,
                        contract_version: _rt::String,
                        request: _rt::Vec<u8>,
                    ) -> Result<_rt::Vec<u8>, PluginError>;
                }
                #[doc(hidden)]
                macro_rules! __export_brolga_plugin_invoke_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "brolga:plugin/invoke@0.1.0#call")] unsafe extern "C" fn
                        export_call(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8, arg3
                        : usize, arg4 : * mut u8, arg5 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_call_cabi::<$ty > (arg0, arg1, arg2,
                        arg3, arg4, arg5) } } #[unsafe (export_name =
                        "cabi_post_brolga:plugin/invoke@0.1.0#call")] unsafe extern "C"
                        fn _post_return_call(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_call::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_brolga_plugin_invoke_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 5 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 5
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::brolga::plugin::manifest::__export_brolga_plugin_manifest_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::brolga::plugin::manifest);
        $($path_to_types_root)*::
        exports::brolga::plugin::invoke::__export_brolga_plugin_invoke_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::brolga::plugin::invoke);
    };
}
#[doc(inline)]
pub(crate) use __export_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:brolga:plugin@0.1.0:plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 444] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xbf\x02\x01A\x02\x01\
A\x07\x01B\x02\x01r\x02\x04codes\x07messages\x04\0\x0cplugin-error\x03\0\0\x03\0\
\x19brolga:plugin/types@0.1.0\x05\0\x02\x03\0\0\x0cplugin-error\x01B\x05\x02\x03\
\x02\x01\x01\x04\0\x0cplugin-error\x03\0\0\x01j\x01s\x01\x01\x01@\0\0\x02\x04\0\x03\
get\x01\x03\x04\0\x1cbrolga:plugin/manifest@0.1.0\x05\x02\x01B\x06\x02\x03\x02\x01\
\x01\x04\0\x0cplugin-error\x03\0\0\x01p}\x01j\x01\x02\x01\x01\x01@\x03\x09extens\
ions\x10contract-versions\x07request\x02\0\x03\x04\0\x04call\x01\x04\x04\0\x1abr\
olga:plugin/invoke@0.1.0\x05\x03\x04\0\x1abrolga:plugin/plugin@0.1.0\x04\0\x0b\x0c\
\x01\0\x06plugin\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-componen\
t\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
