[package]
name = "brolga-query"
description = "Safe structured query language that compiles to typed storage filters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
categories = ["parser-implementations"]
keywords = ["threat-intelligence", "query", "parser"]

[lints]
workspace = true

[dependencies]
brolga-model = { version = "0.1.0", path = "../brolga-model" }
brolga-storage = { version = "0.1.0", path = "../brolga-storage" }
thiserror = "2.0.19"

[dev-dependencies]
