//! Errors produced when constructing or deserialising canonical types.
//!
//! Every error here is reachable from untrusted input, so no variant embeds an unbounded copy of
//! the offending value. Where an error needs to show what it rejected it uses [`preview`], which
//! truncates and escapes. A diagnostic is not a place to replay attacker-controlled bytes.

use core::fmt;

use thiserror::Error;

/// Maximum number of characters of a rejected value that an error message may quote.
const PREVIEW_CHARS: usize = 64;

/// Truncate and escape a rejected value so it is safe to place in a diagnostic.
///
/// Control characters become escape sequences, and anything past 64 characters is replaced by an
/// ellipsis. Truncation counts characters, never bytes, so the result is always valid UTF-8
/// regardless of where the input happened to be cut.
#[must_use]
pub fn preview(value: &str) -> String {
    let mut out = String::new();
    for (count, ch) in value.chars().enumerate() {
        if count >= PREVIEW_CHARS {
            out.push('…');
            break;
        }
        match ch {
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => {
                let escaped = format!("\\u{{{:04x}}}", u32::from(c));
                out.push_str(&escaped);
            }
            c => out.push(c),
        }
    }
    out
}

/// Anything that can go wrong while building or parsing a canonical value.
#[derive(Debug, Error, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum ModelError {
    /// A bounded field was longer than its documented limit.
    #[error("{field} is {actual} bytes, which exceeds the limit of {max} bytes")]
    TooLong {
        /// Name of the field or type that was too long.
        field: &'static str,
        /// The documented limit, in bytes.
        max: usize,
        /// The observed length, in bytes.
        actual: usize,
    },

    /// A field that must carry a value was empty.
    #[error("{field} must not be empty")]
    Empty {
        /// Name of the field or type that was empty.
        field: &'static str,
    },

    /// A field contained a control character that Brolga refuses to store.
    #[error("{field} contains a forbidden control character at character {index}")]
    ForbiddenControlCharacter {
        /// Name of the field or type that carried the character.
        field: &'static str,
        /// Zero-based character index of the first offending character.
        index: usize,
    },

    /// A value failed the syntax rules for its type.
    #[error("invalid {kind}: {reason}")]
    InvalidValue {
        /// The canonical type that rejected the value.
        kind: &'static str,
        /// Why it was rejected. Generated by Brolga, never copied verbatim from input.
        reason: String,
    },

    /// A schema identifier was not in `brolga.<name>/<major>.<minor>` form.
    #[error("schema identifier {found:?} is malformed: {reason}")]
    MalformedSchemaTag {
        /// Truncated, escaped copy of what was found.
        found: String,
        /// Why it was rejected.
        reason: String,
    },

    /// A schema identifier named a different schema than the field expected.
    #[error("expected schema {expected}, found {found:?}")]
    SchemaNameMismatch {
        /// The schema name the field requires.
        expected: &'static str,
        /// Truncated, escaped copy of the name that was found.
        found: String,
    },

    /// A payload declared a major schema version this build cannot interpret.
    ///
    /// This is deliberately an error rather than a best-effort parse. A major version change means
    /// a field was removed, renamed, or retyped, so silently accepting the payload would produce a
    /// record that looks valid and is not.
    #[error(
        "schema {name} major version {found} is not supported by this build, which implements major version {expected}"
    )]
    UnsupportedSchemaMajor {
        /// The schema whose major version did not match.
        name: &'static str,
        /// The major version this build implements.
        expected: u16,
        /// The major version the payload declared.
        found: u16,
    },

    /// An identifier was not in `<kind>:<uuid>` form, or named the wrong kind.
    #[error("invalid identifier {found:?}: {reason}")]
    InvalidId {
        /// Truncated, escaped copy of what was found.
        found: String,
        /// Why it was rejected.
        reason: String,
    },

    /// Two timestamps were supplied in an impossible order.
    #[error("{earlier} ({earlier_value}) must not be later than {later} ({later_value})")]
    TimeOrder {
        /// Name of the field that must come first.
        earlier: &'static str,
        /// RFC 3339 rendering of the earlier field's value.
        earlier_value: String,
        /// Name of the field that must come second.
        later: &'static str,
        /// RFC 3339 rendering of the later field's value.
        later_value: String,
    },

    /// A confidence component was outside the closed range `0..=100`.
    #[error("confidence score {found} is outside the range 0..=100")]
    ConfidenceOutOfRange {
        /// The value that was supplied.
        found: u32,
    },

    /// A sighting claimed to have been observed zero times.
    ///
    /// A sighting is a record that something *was* seen. A count of zero is not a sighting with no
    /// observations; it is a malformed record, and treating it as "seen zero times" would let a
    /// feed inflate the apparent number of independent observations with empty entries.
    #[error("sighting count must be at least 1")]
    ZeroSightingCount,
}

impl ModelError {
    /// Build an [`ModelError::InvalidValue`] without repeating the `reason: ...` boilerplate.
    pub(crate) fn invalid(kind: &'static str, reason: impl fmt::Display) -> Self {
        Self::InvalidValue {
            kind,
            reason: reason.to_string(),
        }
    }
}

/// Convenience alias for fallible canonical-model operations.
pub type Result<T> = core::result::Result<T, ModelError>;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preview_escapes_control_characters() {
        assert_eq!(preview("a\nb\tc\rd"), "a\\nb\\tc\\rd");
        assert_eq!(preview("a\u{0}b"), "a\\u{0000}b");
        assert_eq!(preview("back\\slash"), "back\\\\slash");
    }

    #[test]
    fn preview_truncates_on_a_character_boundary() {
        // Multi-byte characters: truncating by bytes would split one and produce invalid UTF-8.
        let long = "é".repeat(200);
        let previewed = preview(&long);
        assert_eq!(previewed.chars().count(), PREVIEW_CHARS + 1);
        assert!(previewed.ends_with('…'));
    }

    #[test]
    fn preview_leaves_short_plain_values_alone() {
        assert_eq!(preview("example.com"), "example.com");
        assert_eq!(preview(""), "");
    }

    #[test]
    fn unsupported_major_names_both_versions() {
        let error = ModelError::UnsupportedSchemaMajor {
            name: "brolga.entity",
            expected: 1,
            found: 9,
        };
        let rendered = error.to_string();
        assert!(rendered.contains("brolga.entity"), "{rendered}");
        assert!(rendered.contains('9'), "{rendered}");
    }
}
